// integrations/react/components.tsx
/**
 * @fileoverview Ready-to-use React components for FluxHTTP
 */

import React, { Suspense, useCallback, useEffect, useRef } from 'react';
import { useFluxHttp, useFluxHttpMutation } from './useFluxHttp';
import type {
  FetchComponentProps,
  QueryProps,
  MutationProps,
  SuspenseFetchProps,
  ErrorBoundaryFallback,
} from './types';

/**
 * Generic fetch component for declarative data fetching
 * 
 * @example
 * ```tsx
 * <Fetch
 *   url="/api/users"
 *   immediate={true}
 *   fallback={<div>Loading users...</div>}
 *   errorFallback={(error) => <div>Error: {error.message}</div>}
 * >
 *   {({ data, loading, error, refetch }) => {
 *     if (loading) return <div>Loading...</div>;
 *     if (error) return <div>Error: {error.message}</div>;
 *     if (!data) return <div>No data</div>;
 *     
 *     return (
 *       <div>
 *         <ul>
 *           {data.map(user => (
 *             <li key={user.id}>{user.name}</li>
 *           ))}
 *         </ul>
 *         <button onClick={() => refetch()}>Refresh</button>
 *       </div>
 *     );
 *   }}
 * </Fetch>
 * ```
 */
export function Fetch<T = unknown>({
  children,
  fallback,
  errorFallback,
  ...options
}: FetchComponentProps<T>): JSX.Element {
  const state = useFluxHttp<T>(options);

  // Handle loading state
  if (state.loading && fallback) {
    return <>{fallback}</>;
  }

  // Handle error state
  if (state.error && errorFallback) {
    return (
      <>
        {typeof errorFallback === 'function' 
          ? errorFallback(state.error) 
          : errorFallback
        }
      </>
    );
  }

  return <>{children(state)}</>;
}

/**
 * Query component with caching support
 * 
 * @example
 * ```tsx
 * <Query
 *   queryKey={['user', userId]}
 *   url={`/api/users/${userId}`}
 *   immediate={true}
 *   staleTime={5 * 60 * 1000} // 5 minutes
 *   cacheTime={10 * 60 * 1000} // 10 minutes
 *   refetchOnWindowFocus={true}
 * >
 *   {({ data, loading, error, refetch }) => (
 *     <UserProfile 
 *       user={data} 
 *       loading={loading} 
 *       error={error}
 *       onRefresh={refetch}
 *     />
 *   )}
 * </Query>
 * ```
 */
export function Query<T = unknown>({
  queryKey,
  children,
  fallback,
  errorFallback,
  ...options
}: QueryProps<T>): JSX.Element {
  // Generate a stable cache key if provided
  const cacheKey = queryKey ? 
    (Array.isArray(queryKey) ? queryKey.join(':') : queryKey) : 
    undefined;

  const state = useFluxHttp<T>({
    ...options,
    // Use cache key for deduplication if provided
    ...(cacheKey && { dedupingInterval: 5000 }),
  });

  // Handle loading state
  if (state.loading && fallback) {
    return <>{fallback}</>;
  }

  // Handle error state
  if (state.error && errorFallback) {
    return (
      <>
        {typeof errorFallback === 'function' 
          ? errorFallback(state.error) 
          : errorFallback
        }
      </>
    );
  }

  return <>{children(state)}</>;
}

/**
 * Mutation component for handling form submissions and mutations
 * 
 * @example
 * ```tsx
 * <Mutation<User, CreateUserRequest>
 *   onSuccess={(data) => {
 *     toast.success(`User ${data.name} created successfully!`);
 *     navigate(`/users/${data.id}`);
 *   }}
 *   onError={(error) => {
 *     toast.error(`Failed to create user: ${error.message}`);
 *   }}
 * >
 *   {({ mutate, loading, error }) => (
 *     <UserForm
 *       onSubmit={(userData) => {
 *         mutate(userData, {
 *           url: '/api/users',
 *           method: 'POST',
 *         });
 *       }}
 *       loading={loading}
 *       error={error}
 *     />
 *   )}
 * </Mutation>
 * ```
 */
export function Mutation<TData = unknown, TVariables = unknown>({
  children,
  ...options
}: MutationProps<TData, TVariables>): JSX.Element {
  const state = useFluxHttpMutation<TData, TVariables>(options);
  return <>{children(state)}</>;
}

/**
 * Suspense-compatible fetch component
 * 
 * @example
 * ```tsx
 * <Suspense fallback={<div>Loading...</div>}>
 *   <SuspenseFetch url="/api/data">
 *     {(data, refetch) => (
 *       <div>
 *         <pre>{JSON.stringify(data, null, 2)}</pre>
 *         <button onClick={() => refetch()}>Refresh</button>
 *       </div>
 *     )}
 *   </SuspenseFetch>
 * </Suspense>
 * ```
 */
export function SuspenseFetch<T = unknown>({
  url,
  children,
  ...options
}: SuspenseFetchProps<T>): JSX.Element {
  const promiseRef = useRef<Promise<T> | null>(null);
  const dataRef = useRef<T | null>(null);
  const errorRef = useRef<Error | null>(null);

  const { execute } = useFluxHttp<T>({
    ...options,
    url,
    immediate: false,
  });

  const refetch = useCallback(async () => {
    dataRef.current = null;
    errorRef.current = null;
    
    const promise = execute().then(
      (response) => {
        dataRef.current = response.data;
        return response.data;
      },
      (error) => {
        errorRef.current = error;
        throw error;
      }
    );
    
    promiseRef.current = promise;
    return promise;
  }, [execute]);

  // Initialize data fetching
  if (!promiseRef.current && !dataRef.current && !errorRef.current) {
    promiseRef.current = refetch();
  }

  // Throw error if present
  if (errorRef.current) {
    throw errorRef.current;
  }

  // Throw promise for Suspense if data is not ready
  if (!dataRef.current && promiseRef.current) {
    throw promiseRef.current;
  }

  // Render with data
  return <>{children(dataRef.current!, refetch)}</>;
}

/**
 * Error boundary component for handling FluxHTTP errors
 * 
 * @example
 * ```tsx
 * <FluxHttpErrorBoundary
 *   fallback={({ error, retry, reset }) => (
 *     <div className="error-container">
 *       <h2>Something went wrong!</h2>
 *       <p>{error.message}</p>
 *       <div>
 *         <button onClick={retry}>Try Again</button>
 *         <button onClick={reset}>Reset</button>
 *       </div>
 *     </div>
 *   )}
 *   onError={(error, errorInfo) => {
 *     console.error('HTTP Error caught by boundary:', error, errorInfo);
 *     // Log to error reporting service
 *   }}
 * >
 *   <MyComponent />
 * </FluxHttpErrorBoundary>
 * ```
 */
interface FluxHttpErrorBoundaryProps {
  children: React.ReactNode;
  fallback: ErrorBoundaryFallback;
  onError?: (error: Error, errorInfo: React.ErrorInfo) => void;
}

interface FluxHttpErrorBoundaryState {
  hasError: boolean;
  error: Error | null;
}

export class FluxHttpErrorBoundary extends React.Component<
  FluxHttpErrorBoundaryProps,
  FluxHttpErrorBoundaryState
> {
  constructor(props: FluxHttpErrorBoundaryProps) {
    super(props);
    this.state = { hasError: false, error: null };
  }

  static getDerivedStateFromError(error: Error): FluxHttpErrorBoundaryState {
    return { hasError: true, error };
  }

  componentDidCatch(error: Error, errorInfo: React.ErrorInfo) {
    this.props.onError?.(error, errorInfo);
  }

  retry = () => {
    this.setState({ hasError: false, error: null });
  };

  reset = () => {
    this.setState({ hasError: false, error: null });
  };

  render() {
    if (this.state.hasError && this.state.error) {
      return this.props.fallback({
        error: this.state.error as any, // Cast to fluxhttpError for consistency
        retry: this.retry,
        reset: this.reset,
      });
    }

    return this.props.children;
  }
}

/**
 * Loading overlay component
 * 
 * @example
 * ```tsx
 * <LoadingOverlay loading={isLoading} message="Saving changes...">
 *   <UserForm onSubmit={handleSubmit} />
 * </LoadingOverlay>
 * ```
 */
interface LoadingOverlayProps {
  loading: boolean;
  message?: string;
  children: React.ReactNode;
  overlay?: boolean;
  spinner?: React.ReactNode;
}

export function LoadingOverlay({
  loading,
  message = 'Loading...',
  children,
  overlay = true,
  spinner,
}: LoadingOverlayProps): JSX.Element {
  const defaultSpinner = (
    <div 
      style={{
        width: '24px',
        height: '24px',
        border: '2px solid #f3f3f3',
        borderTop: '2px solid #3498db',
        borderRadius: '50%',
        animation: 'spin 1s linear infinite',
      }}
    />
  );

  return (
    <div style={{ position: 'relative' }}>
      {children}
      {loading && (
        <div
          style={{
            position: overlay ? 'absolute' : 'static',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: overlay ? 'rgba(255, 255, 255, 0.8)' : 'transparent',
            zIndex: 1000,
            gap: '12px',
          }}
        >
          {spinner || defaultSpinner}
          {message && <div>{message}</div>}
        </div>
      )}
      <style jsx>{`
        @keyframes spin {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  );
}

/**
 * Infinite scroll component for paginated data
 * 
 * @example
 * ```tsx
 * <InfiniteScroll
 *   url="/api/posts"
 *   pageParam="page"
 *   hasNextPage={(data) => data.hasMore}
 *   getNextPageParam={(data, page) => data.hasMore ? page + 1 : undefined}
 *   renderItem={(item) => <PostCard key={item.id} post={item} />}
 *   renderLoading={() => <div>Loading more posts...</div>}
 *   renderError={(error) => <div>Error: {error.message}</div>}
 * />
 * ```
 */
interface InfiniteScrollProps<T> {
  url: string;
  pageParam?: string;
  hasNextPage: (data: any) => boolean;
  getNextPageParam: (data: any, currentPage: number) => number | undefined;
  renderItem: (item: T) => React.ReactNode;
  renderLoading?: () => React.ReactNode;
  renderError?: (error: any) => React.ReactNode;
  threshold?: number;
}

export function InfiniteScroll<T>({
  url,
  pageParam = 'page',
  hasNextPage,
  getNextPageParam,
  renderItem,
  renderLoading,
  renderError,
  threshold = 100,
}: InfiniteScrollProps<T>): JSX.Element {
  const [page, setPage] = React.useState(1);
  const [allData, setAllData] = React.useState<T[]>([]);
  const [hasMore, setHasMore] = React.useState(true);
  const loadingRef = useRef<HTMLDivElement>(null);

  const { data, loading, error, execute } = useFluxHttp({
    url,
    params: { [pageParam]: page },
    immediate: false,
    onSuccess: (data) => {
      if (page === 1) {
        setAllData(data.items || []);
      } else {
        setAllData(prev => [...prev, ...(data.items || [])]);
      }
      setHasMore(hasNextPage(data));
    },
  });

  // Load initial data
  useEffect(() => {
    execute();
  }, [execute]);

  // Load next page when page changes
  useEffect(() => {
    if (page > 1) {
      execute();
    }
  }, [page, execute]);

  // Intersection observer for infinite scroll
  useEffect(() => {
    if (!hasMore || loading) return;

    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting) {
          const nextPage = getNextPageParam(data, page);
          if (nextPage) {
            setPage(nextPage);
          }
        }
      },
      { threshold: 0.1 }
    );

    if (loadingRef.current) {
      observer.observe(loadingRef.current);
    }

    return () => observer.disconnect();
  }, [hasMore, loading, data, page, getNextPageParam]);

  if (page === 1 && loading) {
    return <>{renderLoading?.() || <div>Loading...</div>}</>;
  }

  if (page === 1 && error) {
    return <>{renderError?.(error) || <div>Error: {error.message}</div>}</>;
  }

  return (
    <div>
      {allData.map(renderItem)}
      {hasMore && (
        <div ref={loadingRef} style={{ padding: '20px', textAlign: 'center' }}>
          {loading && (renderLoading?.() || <div>Loading more...</div>)}
        </div>
      )}
    </div>
  );
}

// integrations/vue/components.vue
<!--
  @fileoverview Vue 3 components for FluxHTTP
-->

<template>
  <!-- This file exports multiple components via script setup -->
  <div>
    <!-- Components are exported via script, not template -->
  </div>
</template>

<script setup lang="ts">
/**
 * Vue 3 components for FluxHTTP integration
 * 
 * This file provides ready-to-use components for common HTTP patterns:
 * - FluxHttpFetch: Generic fetch component
 * - FluxHttpQuery: Query component with caching
 * - FluxHttpMutation: Mutation component for forms
 * - FluxHttpInfiniteScroll: Infinite scrolling component
 * - FluxHttpLoadingOverlay: Loading state overlay
 */

import { 
  defineComponent, 
  h, 
  ref, 
  computed, 
  watch, 
  onMounted, 
  onBeforeUnmount,
  Fragment
} from 'vue';
import { useFluxHttp, useFluxHttpMutation, useInfiniteQuery } from './useFluxHttp';
import type { 
  fluxhttpRequestConfig, 
  fluxhttpError 
} from '../../src/types';

/**
 * Generic fetch component for declarative data fetching
 * 
 * @example
 * ```vue
 * <FluxHttpFetch
 *   url="/api/users"
 *   :immediate="true"
 *   v-slot="{ data, loading, error, refetch }"
 * >
 *   <div v-if="loading">Loading users...</div>
 *   <div v-else-if="error">Error: {{ error.message }}</div>
 *   <ul v-else-if="data">
 *     <li v-for="user in data" :key="user.id">{{ user.name }}</li>
 *   </ul>
 *   <button @click="refetch">Refresh</button>
 * </FluxHttpFetch>
 * ```
 */
export const FluxHttpFetch = defineComponent({
  name: 'FluxHttpFetch',
  props: {
    url: String,
    method: {
      type: String,
      default: 'GET'
    },
    params: Object,
    data: null,
    immediate: {
      type: Boolean,
      default: true
    },
    headers: Object,
    timeout: Number,
    loadingTemplate: String,
    errorTemplate: String,
    emptyTemplate: String,
  },
  setup(props, { slots }) {
    const config = computed((): fluxhttpRequestConfig => ({
      url: props.url,
      method: props.method as any,
      params: props.params,
      data: props.data,
      headers: props.headers,
      timeout: props.timeout,
    }));

    const state = useFluxHttp({
      ...config.value,
      immediate: props.immediate,
    });

    // Watch for prop changes
    watch(
      () => [props.url, props.method, props.params, props.data],
      () => {
        if (props.immediate && props.url) {
          state.execute();
        }
      },
      { deep: true }
    );

    return () => {
      const slotProps = {
        data: state.data.value,
        loading: state.loading.value,
        error: state.error.value,
        response: state.response.value,
        success: state.success.value,
        execute: state.execute,
        refetch: state.refetch,
        cancel: state.cancel,
        reset: state.reset,
        mutate: state.mutate,
      };

      // Use default slot if provided
      if (slots.default) {
        return slots.default(slotProps);
      }

      // Fallback rendering
      if (state.loading.value) {
        return h('div', { class: 'fluxhttp-loading' }, props.loadingTemplate || 'Loading...');
      }

      if (state.error.value) {
        return h('div', { class: 'fluxhttp-error' }, 
          props.errorTemplate || `Error: ${state.error.value.message}`
        );
      }

      if (!state.data.value) {
        return h('div', { class: 'fluxhttp-empty' }, props.emptyTemplate || 'No data');
      }

      return h('pre', JSON.stringify(state.data.value, null, 2));
    };
  },
});

/**
 * Query component with caching support
 * 
 * @example
 * ```vue
 * <FluxHttpQuery
 *   :query-key="['user', userId]"
 *   :url="`/api/users/${userId}`"
 *   :stale-time="5 * 60 * 1000"
 *   :cache-time="10 * 60 * 1000"
 *   :refetch-on-window-focus="true"
 *   v-slot="{ data, loading, error, refetch }"
 * >
 *   <UserProfile 
 *     :user="data" 
 *     :loading="loading" 
 *     :error="error"
 *     @refresh="refetch"
 *   />
 * </FluxHttpQuery>
 * ```
 */
export const FluxHttpQuery = defineComponent({
  name: 'FluxHttpQuery',
  props: {
    queryKey: [String, Array],
    url: String,
    method: {
      type: String,
      default: 'GET'
    },
    params: Object,
    data: null,
    immediate: {
      type: Boolean,
      default: true
    },
    enabled: {
      type: Boolean,
      default: true
    },
    staleTime: Number,
    cacheTime: Number,
    refetchOnWindowFocus: Boolean,
    refetchOnReconnect: Boolean,
    keepPreviousData: Boolean,
  },
  setup(props, { slots }) {
    const config = computed((): fluxhttpRequestConfig => ({
      url: props.url,
      method: props.method as any,
      params: props.params,
      data: props.data,
    }));

    const state = useFluxHttp({
      ...config.value,
      immediate: props.immediate && props.enabled,
      staleTime: props.staleTime,
      cacheTime: props.cacheTime,
      refetchOnWindowFocus: props.refetchOnWindowFocus,
      refetchOnReconnect: props.refetchOnReconnect,
      keepPreviousData: props.keepPreviousData,
    });

    // Watch enabled state
    watch(() => props.enabled, (enabled) => {
      if (enabled && !state.data.value && !state.loading.value) {
        state.execute();
      }
    });

    return () => {
      const slotProps = {
        data: state.data.value,
        loading: state.loading.value,
        error: state.error.value,
        response: state.response.value,
        success: state.success.value,
        execute: state.execute,
        refetch: state.refetch,
        cancel: state.cancel,
        reset: state.reset,
        mutate: state.mutate,
        isFresh: state.isFresh.value,
        isStale: state.isStale.value,
      };

      return slots.default?.(slotProps) || null;
    };
  },
});

/**
 * Mutation component for handling form submissions and mutations
 * 
 * @example
 * ```vue
 * <FluxHttpMutation
 *   @success="onUserCreated"
 *   @error="onError"
 *   v-slot="{ mutate, loading, error }"
 * >
 *   <UserForm
 *     @submit="(userData) => mutate(userData, { url: '/api/users', method: 'POST' })"
 *     :loading="loading"
 *     :error="error"
 *   />
 * </FluxHttpMutation>
 * ```
 */
export const FluxHttpMutation = defineComponent({
  name: 'FluxHttpMutation',
  emits: ['success', 'error', 'settled', 'mutate'],
  setup(props, { slots, emit }) {
    const state = useFluxHttpMutation({
      onSuccess: (data, variables, response) => {
        emit('success', data, variables, response);
      },
      onError: (error, variables) => {
        emit('error', error, variables);
      },
      onSettled: (data, error, variables) => {
        emit('settled', data, error, variables);
      },
      onMutate: (variables) => {
        emit('mutate', variables);
      },
    });

    return () => {
      const slotProps = {
        data: state.data.value,
        loading: state.loading.value,
        error: state.error.value,
        response: state.response.value,
        success: state.success.value,
        variables: state.variables.value,
        mutate: state.mutate,
        mutateAsync: state.mutateAsync,
        reset: state.reset,
      };

      return slots.default?.(slotProps) || null;
    };
  },
});

/**
 * Infinite scroll component for paginated data
 * 
 * @example
 * ```vue
 * <FluxHttpInfiniteScroll
 *   url="/api/posts"
 *   page-param="page"
 *   :get-next-page-param="(data, page) => data.hasMore ? page + 1 : undefined"
 *   v-slot="{ data, loading, hasNextPage, fetchNextPage }"
 * >
 *   <PostCard v-for="post in data" :key="post.id" :post="post" />
 *   <button 
 *     v-if="hasNextPage" 
 *     @click="fetchNextPage"
 *     :disabled="loading"
 *   >
 *     Load More
 *   </button>
 * </FluxHttpInfiniteScroll>
 * ```
 */
export const FluxHttpInfiniteScroll = defineComponent({
  name: 'FluxHttpInfiniteScroll',
  props: {
    url: {
      type: String,
      required: true
    },
    pageParam: {
      type: String,
      default: 'page'
    },
    getNextPageParam: {
      type: Function,
      required: true
    },
    getPreviousPageParam: Function,
    initialPageParam: {
      default: 1
    },
    maxPages: {
      type: Number,
      default: Infinity
    },
    threshold: {
      type: Number,
      default: 100
    },
    autoLoad: {
      type: Boolean,
      default: true
    },
    immediate: {
      type: Boolean,
      default: true
    },
  },
  setup(props, { slots }) {
    const state = useInfiniteQuery({
      url: props.url,
      getNextPageParam: props.getNextPageParam,
      getPreviousPageParam: props.getPreviousPageParam,
      initialPageParam: props.initialPageParam,
      maxPages: props.maxPages,
      immediate: props.immediate,
    });

    const sentinel = ref<HTMLElement>();
    const observer = ref<IntersectionObserver>();

    onMounted(() => {
      if (props.autoLoad && sentinel.value) {
        observer.value = new IntersectionObserver(
          (entries) => {
            if (entries[0].isIntersecting && state.hasNextPage.value && !state.isFetchingNextPage.value) {
              state.fetchNextPage();
            }
          },
          { threshold: 0.1 }
        );
        observer.value.observe(sentinel.value);
      }
    });

    onBeforeUnmount(() => {
      if (observer.value) {
        observer.value.disconnect();
      }
    });

    return () => {
      const slotProps = {
        data: state.data.value,
        loading: state.loading.value,
        error: state.error.value,
        success: state.success.value,
        hasNextPage: state.hasNextPage.value,
        hasPreviousPage: state.hasPreviousPage.value,
        isFetchingNextPage: state.isFetchingNextPage.value,
        isFetchingPreviousPage: state.isFetchingPreviousPage.value,
        fetchNextPage: state.fetchNextPage,
        fetchPreviousPage: state.fetchPreviousPage,
        refetch: state.refetch,
        reset: state.reset,
      };

      const children = [
        slots.default?.(slotProps),
      ];

      // Add sentinel for auto-loading
      if (props.autoLoad && state.hasNextPage.value) {
        children.push(
          h('div', {
            ref: sentinel,
            style: { height: '1px' }
          })
        );
      }

      return h(Fragment, children);
    };
  },
});

/**
 * Loading overlay component
 * 
 * @example
 * ```vue
 * <FluxHttpLoadingOverlay 
 *   :loading="isLoading" 
 *   message="Saving changes..."
 *   :overlay="true"
 * >
 *   <UserForm @submit="handleSubmit" />
 * </FluxHttpLoadingOverlay>
 * ```
 */
export const FluxHttpLoadingOverlay = defineComponent({
  name: 'FluxHttpLoadingOverlay',
  props: {
    loading: {
      type: Boolean,
      default: false
    },
    message: {
      type: String,
      default: 'Loading...'
    },
    overlay: {
      type: Boolean,
      default: true
    },
    spinner: {
      type: Boolean,
      default: true
    },
  },
  setup(props, { slots }) {
    const defaultSpinner = () => h('div', {
      class: 'fluxhttp-spinner',
      style: {
        width: '24px',
        height: '24px',
        border: '2px solid #f3f3f3',
        borderTop: '2px solid #3498db',
        borderRadius: '50%',
        animation: 'fluxhttp-spin 1s linear infinite',
      }
    });

    return () => {
      const children = [slots.default?.()];

      if (props.loading) {
        const loadingContent = [
          props.spinner && (slots.spinner?.() || defaultSpinner()),
          props.message && h('div', { class: 'fluxhttp-loading-message' }, props.message),
        ].filter(Boolean);

        children.push(
          h('div', {
            class: 'fluxhttp-loading-overlay',
            style: {
              position: props.overlay ? 'absolute' : 'static',
              top: 0,
              left: 0,
              right: 0,
              bottom: 0,
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'center',
              backgroundColor: props.overlay ? 'rgba(255, 255, 255, 0.8)' : 'transparent',
              zIndex: 1000,
              gap: '12px',
            }
          }, loadingContent)
        );
      }

      return h('div', {
        class: 'fluxhttp-loading-container',
        style: { position: 'relative' }
      }, children);
    };
  },
});

// CSS for animations
const style = document.createElement('style');
style.textContent = `
  @keyframes fluxhttp-spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }
`;
document.head.appendChild(style);
</script>

<style scoped>
.fluxhttp-loading {
  padding: 20px;
  text-align: center;
  color: #666;
}

.fluxhttp-error {
  padding: 20px;
  text-align: center;
  color: #e74c3c;
  background-color: #fdf2f2;
  border: 1px solid #f1c1c1;
  border-radius: 4px;
}

.fluxhttp-empty {
  padding: 20px;
  text-align: center;
  color: #999;
  font-style: italic;
}

.fluxhttp-loading-container {
  position: relative;
}

.fluxhttp-loading-overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  background-color: rgba(255, 255, 255, 0.8);
  z-index: 1000;
}

.fluxhttp-spinner {
  width: 24px;
  height: 24px;
  border: 2px solid #f3f3f3;
  border-top: 2px solid #3498db;
  border-radius: 50%;
  animation: fluxhttp-spin 1s linear infinite;
}

.fluxhttp-loading-message {
  margin-top: 12px;
  color: #666;
  font-size: 14px;
}

@keyframes fluxhttp-spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style>
